### ISSUE TITLE
RTP flags and AF

### ISSUE THREAD

**Issue by barteqcz** [Anthony96922/MiniRDS#5]
Hello! I have two questions/issues with MiniRDS.

1. The first thing is that when I try to execute 'RTPF 1,0' from FIFO, to set the running bit to 1 and enable RT+, it doesn't change the running bit, but either the toggle bit, or nothing at all.
2. The second thing is more like a suggestion/question - when sending AF, MiniRDS sends it, probably, incorrectly, using method B. I mean, it makes a list, but using method B. Shouldn't it transmit the AF using method A, so that it would be a normal, max. 25 freq list?

**Comment by Anthony96922** [comment]
1. The syntax for RTP was changed to a bitmask. A 2-bit integer is now used to convey the intended running/toggle flags. 1 sets toggle only, 2 sets running only and 3 sets both flags.
2. The AF parser logic is flexible enough to allow either method A or B. See section 7.5.2 in the IEC 62106-2 spec for more info. Here is an example command you can try for method B coding: `AF s 100.7 100.7 96.1`

**Comment by barteqcz** [comment]
Thank you very much! Now I understand everything. Also - very nice approach for the RT+ bits. Shorter, but also easy to understand. AF A working too. I just passed every frequency as a separate command to FIFO, and that's why it was saving it as method B. Thank you, once again, for your help. 😄
